# frozen_string_literal: true

# Builds the single-file eohunter.lic that Lich's installers can carry.
#
# The repo keeps the engine as parts under scripts/eohunter/, one file
# each, which is what the specs load. Lich's ;repo fetches one script
# file and jinx installs assets flat, so neither can place that
# directory. This builder inlines the parts into scripts/eohunter.lic's
# body, in engine.rb's PARTS order, where the load line was:
#
#   ruby tools/build.rb            # writes dist/eohunter.lic and its map
#   bundle exec rake build         # the same
#
# The map (dist/eohunter.lic.map) lists each part's first and last line
# in the built file, so a line number in a Lich error traces back to
# the part it came from.
#
# Pure Ruby, no Lich: runs anywhere the repo is checked out.
module EOHunter
  # The single-file builder: inlines the engine parts into eohunter.lic's
  # body and writes the line map. Pure Ruby, no Lich.
  module Build
    # The one line in eohunter.lic the inlined parts replace.
    LOAD_LINE = "load File.join(SCRIPT_DIR, 'eohunter', 'engine.rb')"
    # engine.rb's last line, dropped from the built file.
    LOAD_PARTS_LINE = 'EO::Engine.load_parts'
    # The frozen_string_literal pragma and the blank line after it.
    PRAGMA = /\A# frozen_string_literal: true\r?\n\r?\n?/
    # The section marker written above each inlined part (format with its name).
    MARKER = '# ==== %s ===='

    # A build: the source text and `{part name => [first line, last line]}`.
    Result = Struct.new(:source, :sections, keyword_init: true)

    module_function

    # The built source and its part map, without touching the disk.
    #
    # @param root [String] the repo root
    # @param sha [String, nil] what to record as the build's commit
    # @return [Result]
    def build(root:, sha: nil)
      script = read(root, 'scripts/eohunter.lic')
      head, tail = split_at_load(script)
      engine = read(root, 'scripts/eohunter/engine.rb')
      parts = parts_of(engine)

      lines = []
      lines.concat(head.lines)
      lines << "# Built from the parts under scripts/eohunter/ (commit #{sha || 'unknown'}).\n"
      lines << "# Edit the parts and rebuild; do not edit this file in place.\n"
      lines << "\n"
      map = {}
      append_marked(lines, map, 'eohunter/engine.rb', strip_load_parts(strip_pragma(engine)))
      lines.concat(inline_loader(sha).lines)
      parts.each do |part|
        source = strip_pragma(read(root, "scripts/eohunter/#{part}.rb"))
        source = setup_source(source, part) if part.start_with?('setup/')
        append_marked(lines, map, "eohunter/#{part}.rb", source)
      end
      lines << "#{format(MARKER, 'eohunter.lic')}\n"
      lines.concat(tail.lines)
      Result.new(source: lines.join, sections: map)
    end

    # Writes dist/eohunter.lic and dist/eohunter.lic.map under +root+.
    #
    # @param root [String] the repo root
    # @param out [String] where the built script goes; the map is out + ".map"
    # @param sha [String, nil] what to record as the build's commit
    # @return [String] the path written
    def write(root:, out: File.join(root, 'dist', 'eohunter.lic'), sha: git_sha(root))
      result = build(root: root, sha: sha)
      Dir.mkdir(File.dirname(out)) unless Dir.exist?(File.dirname(out))
      File.write(out, result.source, mode: 'wb')
      File.write("#{out}.map", map_text(result.sections), mode: 'wb')
      out
    end

    # A repo file as text with Unix line endings.
    #
    # @param root [String] the repo root
    # @param relative [String] the path under it
    # @return [String]
    # @raise [ArgumentError] when the file is missing
    def read(root, relative)
      path = File.join(root, relative)
      raise ArgumentError, "missing #{relative}" unless File.exist?(path)

      File.read(path, mode: 'rb').gsub("\r\n", "\n")
    end

    # The script split around its one load line: everything before it
    # (the header, the constant check, the requires) and everything after.
    #
    # @param script [String] eohunter.lic's source
    # @return [Array(String, String)] head and tail
    # @raise [ArgumentError] unless exactly one load line is found
    def split_at_load(script)
      lines = script.lines
      at = lines.each_index.select { |i| lines[i].chomp == LOAD_LINE }
      raise ArgumentError, "expected exactly one load line in eohunter.lic, found #{at.size}" unless at.size == 1

      [lines[0...at.first].join, lines[(at.first + 1)..].join]
    end

    # engine.rb's PARTS, in order.
    #
    # @param engine [String] engine.rb's source
    # @return [Array<String>] the part names
    # @raise [ArgumentError] when no PARTS list is found
    def parts_of(engine)
      m = engine.match(/PARTS = %w\[(.*?)\]/m)
      raise ArgumentError, 'engine.rb has no PARTS list' unless m

      m[1].split
    end

    # The source without its frozen_string_literal pragma.
    # @param source [String]
    # @return [String]
    def strip_pragma(source) = source.sub(PRAGMA, '')

    # Shared setup readers survive Engine reload; bundled dependencies are inline.
    # @param source [String] one setup module's source
    # @param part [String] setup/name, matching its class
    # @return [String] guarded source without relative disk dependencies
    def setup_source(source, part)
      name = File.basename(part).split('_').map(&:capitalize).join
      body = source.gsub(/^require_relative .*\n/, '').sub(/^module EO$/, 'module ::EO')
      "unless defined?(::EO::HunterSetup::#{name})\n#{body}end\n"
    end

    # engine.rb ends by loading the parts from its directory; the built
    # file has them inline instead.
    #
    # @param engine [String] engine.rb's source
    # @return [String] the source without its last load_parts line, one
    #   trailing newline
    # @raise [ArgumentError] when the line is absent
    def strip_load_parts(engine)
      lines = engine.lines
      at = lines.rindex { |l| l.chomp == LOAD_PARTS_LINE }
      raise ArgumentError, "engine.rb does not end with #{LOAD_PARTS_LINE}" unless at

      lines.delete_at(at)
      lines.join.sub(/\n+\z/, "\n")
    end

    # load_parts must find nothing to do in the built file, and the
    # script can say which commit it was built from.
    #
    # @param sha [String, nil] the commit, "unknown" when nil
    # @return [String] a module block defining BUILT_FROM and a no-op load_parts
    def inline_loader(sha)
      <<~RUBY

        module ::EO
          module Engine
            BUILT_FROM = #{(sha || 'unknown').inspect}.freeze

            # The parts are inlined below; nothing on disk to load.
            def self.load_parts(_dir = nil) = true
          end
        end

      RUBY
    end

    # Append one part under its marker and record its first and last line
    # (1-based, in the built file) in the map.
    #
    # @param lines [Array<String>] the built file so far, mutated
    # @param map [Hash{String => Array(Integer, Integer)}] the sections, mutated
    # @param name [String] the part's name for the marker and the map
    # @param source [String] the part's source
    # @return [Array<String>] the lines
    def append_marked(lines, map, name, source)
      lines << "#{format(MARKER, name)}\n"
      first = lines.size + 1
      lines.concat(source.lines)
      lines << "\n" unless lines.last.end_with?("\n")
      map[name] = [first, lines.size]
      lines << "\n"
    end

    # The map file's text: one line per part, name then first and last line.
    #
    # @param map [Hash{String => Array(Integer, Integer)}] the sections
    # @return [String]
    def map_text(map)
      width = map.keys.map(&:size).max
      map.map { |name, (first, last)| format("%-#{width}s %6d %6d\n", name, first, last) }.join
    end

    # The short HEAD sha of the checkout at root; nil without git or a repo.
    #
    # @param root [String] the repo root
    # @return [String, nil]
    def git_sha(root)
      sha = `git -C "#{root}" rev-parse --short HEAD 2>#{File::NULL}`.strip
      sha.empty? ? nil : sha
    rescue StandardError
      nil
    end
  end
end

if $PROGRAM_NAME == __FILE__
  root = File.expand_path('..', __dir__)
  args = ARGV.dup
  # Anything starting with - is a flag, not a destination: every argument
  # used to be expanded into an output path, so `build.rb --check` wrote a
  # file literally named "--check".
  flags, rest = args.partition { |a| a.start_with?('-') }
  unknown = flags - ['--check', '-h', '--help']
  if !unknown.empty? || flags.any? { |f| ['-h', '--help'].include?(f) }
    warn("unknown option: #{unknown.join(' ')}") unless unknown.empty?
    warn('usage: build.rb [--check] [output path]')
    exit(unknown.empty? ? 0 : 1)
  end

  if flags.include?('--check')
    # Build in memory and report, without touching dist/.
    result = EOHunter::Build.build(root: root)
    puts "built #{result.source.lines.size} lines from #{result.sections.size} sections (nothing written)"
    exit 0
  end

  out = rest[0] ? File.expand_path(rest[0]) : File.join(root, 'dist', 'eohunter.lic')
  path = EOHunter::Build.write(root: root, out: out)
  puts "built #{path} (#{File.read(path).lines.size} lines), map at #{path}.map"
end
