# frozen_string_literal: true

require_relative 'build'

# Build support for the independently loadable coordination library.
module EOCoordination
  # Produces the single-file library that Lich's flat script installers can
  # carry. The files stay separate in source so each protocol boundary remains
  # reviewable and independently testable.
  module Build
    # Dependency-ordered source parts in the self-contained artifact.
    PARTS = %w[bounded_frame server client operations protocol discovery parser_projection].freeze
    # Development loader replaced by the inlined source parts.
    LOAD_BLOCK = <<~RUBY.freeze
      base = File.join(SCRIPT_DIR, 'eocoordination')
      verbose = $VERBOSE
      begin
        $VERBOSE = nil
        load File.join(base, 'protocol.rb')
        load File.join(base, 'discovery.rb')
        load File.join(base, 'parser_projection.rb')
      ensure
        $VERBOSE = verbose
      end
    RUBY

    module_function

    # Build the library and its source-line section map without writing files.
    # @param root [String] repository root
    # @param sha [String, nil] commit recorded in the generated header
    # @return [EOHunter::Build::Result]
    def build(root:, sha: nil)
      script = EOHunter::Build.read(root, 'scripts/libeocoordination.lic')
      pieces = script.split(LOAD_BLOCK, -1)
      raise ArgumentError, "expected exactly one coordination load block, found #{pieces.size - 1}" unless pieces.size == 2

      lines = pieces.first.lines
      lines << "# Built from scripts/eocoordination/ (commit #{sha || 'unknown'}).\n"
      lines << "# Edit the parts and rebuild; do not edit this file in place.\n\n"
      # Source files are loaded at top level; Lich evaluates the flat artifact
      # inside Lich::Common. Keep the bundled definitions in their source scope.
      lines << "Object.const_set(:EO, Module.new) unless Object.const_defined?(:EO, false)\n"
      sections = {}
      PARTS.each do |part|
        source = EOHunter::Build.read(root, "scripts/eocoordination/#{part}.rb")
        source = EOHunter::Build.strip_pragma(source)
        source = source.lines.reject { |line| line.start_with?('require_relative ') }.join
        source = source.gsub(/^module EO$/, 'module ::EO')
        EOHunter::Build.append_marked(lines, sections, "eocoordination/#{part}.rb", source)
      end
      lines << "#{format(EOHunter::Build::MARKER, 'libeocoordination.lic')}\n"
      lines.concat(pieces.last.lines)
      EOHunter::Build::Result.new(source: lines.join, sections: sections)
    end

    # Write dist/libeocoordination.lic and its source-line map.
    # @param root [String] repository root
    # @param out [String] output file; the map uses +out+ plus `.map`
    # @param sha [String, nil] commit recorded in the generated header
    # @return [String] output path
    def write(root:, out: File.join(root, 'dist', 'libeocoordination.lic'), sha: EOHunter::Build.git_sha(root))
      result = build(root: root, sha: sha)
      Dir.mkdir(File.dirname(out)) unless Dir.exist?(File.dirname(out))
      File.write(out, result.source, mode: 'wb')
      File.write("#{out}.map", EOHunter::Build.map_text(result.sections), mode: 'wb')
      out
    end
  end
end

if $PROGRAM_NAME == __FILE__
  root = File.expand_path('..', __dir__)
  if ARGV == ['--check']
    result = EOCoordination::Build.build(root: root)
    puts "built #{result.source.lines.size} lines from #{result.sections.size} sections (nothing written)"
  elsif ARGV.empty? || (ARGV.size == 1 && !ARGV.first.start_with?('-'))
    out = ARGV.first ? File.expand_path(ARGV.first) : File.join(root, 'dist', 'libeocoordination.lic')
    path = EOCoordination::Build.write(root: root, out: out)
    puts "built #{path} (#{File.read(path).lines.size} lines), map at #{path}.map"
  else
    warn('usage: build_coordination.rb [--check] [output path]')
    exit 1
  end
end
